name: Build with cache
on: [push]

jobs:
  build:
    name: MATLAB Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: matlab-actions/setup-matlab@v3
        with:
          release: latest-including-prerelease
          cache: true

      - uses: actions/cache/restore@v6
        with:
          path: .buildtool
          key: matlab-buildtool-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            matlab-buildtool-${{ runner.os }}-

      - uses: matlab-actions/run-build@v3
        with:
          build-options: -outputCache

      - if: github.ref == 'refs/heads/main'
        uses: actions/cache/save@v5
        with:
          path: .buildtool
          key: matlab-buildtool-${{ runner.os }}-${{ github.ref_name }}
